apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-public-pvc
  namespace: wcr
  labels:
    app: invoiceninja
    component: application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-storage-pvc
  namespace: wcr
  labels:
    app: invoiceninja
    component: application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

