import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import http from 'node:http';import https from 'node:https';import {execFile,execFileSync} from 'node:child_process';import {promisify} from 'node:util';
import {check,same,run} from '../lib/check.mjs';import {ROOT} from '../lib/paths.mjs';
const execute=promisify(execFile),dir=fs.mkdtempSync(path.join(os.tmpdir(),'teamwork-boundaries-')),sockets=new Set(),servers=[];
const listFile=path.join(dir,'list.json'),out=path.join(dir,'out'),history=path.join(dir,'history');fs.mkdirSync(out);fs.mkdirSync(history);
const program=(id,probe)=>({id,name:id,purpose:'Erfundenes Testprogramm',url:'https://'+id+'.example.test/',zone:'zone',probe});
function list(programs){fs.writeFileSync(listFile,JSON.stringify({format:1,zones:[{id:'zone',name:'Testzone',color:'cyan'}],programs}));}
async function serve(server){servers.push(server);server.on('connection',(socket)=>{sockets.add(socket);socket.on('error',()=>{});socket.on('close',()=>sockets.delete(socket));});await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));return server.address().port;}
async function cli(args=[],env=process.env){const start=Date.now();try{const r=await execute('python3',[path.join(ROOT,'status/teamwork_status.py'),'--list',listFile,'--out',out,'--history',history,'--retry-delay','.1',...args],{timeout:20000,env});return {...r,code:0,ms:Date.now()-start};}catch(e){return {code:e.code,stdout:e.stdout||'',stderr:e.stderr||'',ms:Date.now()-start};}}
try{await run(async()=>{
 const statusline=await serve(net.createServer((socket)=>{socket.resume();socket.write('HTTP/1.1 200 OK\r\n');}));list([program('line','http://127.0.0.1:'+statusline+'/')]);const line=await cli(['--timeout','1']);check('C9 status line below 500 is reachable without waiting for headers',line.code===0&&JSON.parse(fs.readFileSync(path.join(out,'status.json'))).reachable.join()==='line');
 const times=[];const recovering=http.createServer((req,res)=>{times.push(Date.now());res.writeHead(times.length===1?503:200);res.end();});const rp=await serve(recovering);list([program('recovered','http://127.0.0.1:'+rp+'/')]);const retry=await cli(['--retry-delay','1']);
 check('C11 first failure then success gets two probes with required retry delay',retry.code===0&&times.length===2&&times[1]-times[0]>=1000&&times[1]-times[0]<2000);
 same('C11 successful second attempt becomes reachable',JSON.parse(fs.readFileSync(path.join(out,'status.json'))).reachable,['recovered']);
 const scheduleTimes=[];const queued=await serve(http.createServer((req,res)=>{if(req.url==='/retry'){scheduleTimes.push(Date.now());res.writeHead(scheduleTimes.length===1?503:200);res.end();}else setTimeout(()=>{res.writeHead(200);res.end();},600);}));list([program('retry','http://127.0.0.1:'+queued+'/retry'),...Array.from({length:4},(_,i)=>program('queued-'+i,'http://127.0.0.1:'+queued+'/slow'))]);const scheduled=await cli(['--parallel','1']);check('C11 an eligible retry precedes unrelated queued first checks',scheduled.code===0&&scheduleTimes.length===2&&scheduleTimes[1]-scheduleTimes[0]<1100);
 const invalid=await serve(net.createServer((socket)=>socket.end('not HTTP\r\n')));const closed=net.createServer();await new Promise((resolve)=>closed.listen(0,'127.0.0.1',resolve));const cp=closed.address().port;await new Promise((resolve)=>closed.close(resolve));
 execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',path.join(dir,'key.pem'),'-out',path.join(dir,'cert.pem'),'-days','1','-subj','/CN=localhost','-addext','subjectAltName=IP:127.0.0.1'],{stdio:'ignore'});
 const secure=await serve(https.createServer({key:fs.readFileSync(path.join(dir,'key.pem')),cert:fs.readFileSync(path.join(dir,'cert.pem'))},(req,res)=>{res.writeHead(401);res.end();}));
 list([program('protocol','http://127.0.0.1:'+invalid+'/'),program('refused','http://127.0.0.1:'+cp+'/'),program('tls','https://127.0.0.1:'+secure+'/')]);const failures=await cli();
 check('C9 malformed protocol, refused socket and self-signed TLS stay unreachable',failures.code===0&&JSON.parse(fs.readFileSync(path.join(out,'status.json'))).reachable.length===0&&['protocol','refused','tls'].every((reason)=>failures.stdout.includes('reason='+reason)));
 list([program('trusted','https://127.0.0.1:'+secure+'/')]);const trusted=await cli([],{...process.env,SSL_CERT_FILE:path.join(dir,'cert.pem')});check('C10 trusted HTTPS probe below 500 is reachable',trusted.code===0&&JSON.parse(fs.readFileSync(path.join(out,'status.json'))).reachable.join()==='trusted');
 let active=0,peak=0;const hung=await serve(net.createServer((socket)=>{socket.resume();active++;peak=Math.max(peak,active);socket.on('close',()=>active--);}));list(Array.from({length:21},(_,i)=>program('hang-'+i,'http://127.0.0.1:'+hung+'/')));
 const bounded=await cli(['--connect-timeout','1','--timeout','2','--retry-delay','3']);check('C13 21 hung probes finish within 17 seconds with at most eight parallel sockets',bounded.code===0&&bounded.ms<=17000&&peak<=8,JSON.stringify({code:bounded.code,ms:bounded.ms,peak}));
 const publicFiles=['programs.json','status.json'],before=publicFiles.map((name)=>fs.readFileSync(path.join(out,name)));
 const capped=await cli(['--connect-timeout','1','--timeout','2','--retry-delay','3','--max-run','5']);
 const unchanged=publicFiles.map((name,index)=>before[index].equals(fs.readFileSync(path.join(out,name))));
 check('C14 five-second cap exits 4 within six seconds and leaves public outputs intact',capped.code===4&&capped.ms<=6000&&unchanged.every(Boolean),JSON.stringify({code:capped.code,ms:capped.ms,programsUnchanged:unchanged[0],statusUnchanged:unchanged[1],stderr:capped.stderr.trim().slice(-160)}));
});}finally{for(const socket of sockets)socket.destroy();for(const server of servers)await new Promise((resolve)=>server.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
