import { useMemo, useState } from "react";
import { DownloadIcon, ExternalLinkIcon, LanguagesIcon, LogOutIcon, SearchIcon, ShieldCheckIcon } from "lucide-react";
import { api } from "@/api";
import { labelFixture, labelLifecycle, labelProject, labelTopic, t, type Locale } from "@/i18n";
import { domainClass, sortAccountsForWork } from "@/presentation";
import { AccountCard } from "./account-card";
import { AccountDetailSheet } from "./account-detail-sheet";
import { AccountTable } from "./account-table";
import { MetadataEditor } from "./metadata-editor";
import { TaxonomySettings } from "./taxonomy-settings";
import { VersionBulkAction } from "./version-bulk-action";
import { MultiSelect } from "./multi-select";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "@/components/ui/empty";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import type { AccountMetadata, AccountView, FixtureQuality, LifecycleStatus, Project, Taxonomies } from "@/types";

const domains = ["all", "dreambau.com", "dreambau.de", "getme.global", "openresilience.cc", "oriso.org", "trail.ist"];
const lifecycleValues: Array<"all" | LifecycleStatus> = ["all", "unused", "active", "needs_review", "delete_candidate", "archived"];
const fixtureValues: Array<"all" | FixtureQuality> = ["all", "empty", "synthetic", "realistic", "gold"];
const projectValues: Array<"all" | Project> = ["all", "NONE", "ORI", "ORISO", "ORIMO", "TRAIL.IST", "DREAMBAU", "OTHER"];
const WEBMAIL_URL = "https://mail.dreambau.com/";

export function AccountDirectory({ initialAccounts, initialTaxonomies, locale, onLocaleChange, onLogout }: { initialAccounts: AccountView[]; initialTaxonomies: Taxonomies; locale: Locale; onLocaleChange: (locale: Locale) => void; onLogout: () => void }) {
  const [accounts, setAccounts] = useState(initialAccounts); const [taxonomies, setTaxonomies] = useState(initialTaxonomies);
  const [query, setQuery] = useState(""); const [domain, setDomain] = useState("all"); const [status, setStatus] = useState<"all" | LifecycleStatus>("all"); const [quality, setQuality] = useState<"all" | FixtureQuality>("all"); const [project, setProject] = useState<"all" | Project>("all");
  const [versionAfter, setVersionAfter] = useState(""); const [roleFilters, setRoleFilters] = useState<string[]>([]); const [topicFilters, setTopicFilters] = useState<string[]>([]); const [conversationFilters, setConversationFilters] = useState<string[]>([]);
  const [selected, setSelected] = useState<AccountView | null>(null); const [detailOpen, setDetailOpen] = useState(false); const [editOpen, setEditOpen] = useState(false);
  const filtered = useMemo(() => sortAccountsForWork(accounts.filter((account) => {
    const haystack = [account.displayName, account.email, account.domain, account.metadata.shippedVersion, account.metadata.lifecycleStatus, account.metadata.project, account.metadata.fixtureQuality, account.metadata.notes, ...account.metadata.roles, ...account.metadata.topics, ...account.metadata.conversationTypes].join(" ").toLowerCase();
    const aboveVersion = !versionAfter || (account.metadata.shippedVersion && compareVersions(account.metadata.shippedVersion, versionAfter) > 0);
    return (domain === "all" || account.domain === domain) && (status === "all" || account.metadata.lifecycleStatus === status) && (project === "all" || account.metadata.project === project) && (quality === "all" || account.metadata.fixtureQuality === quality) && aboveVersion && roleFilters.every((item) => account.metadata.roles.includes(item)) && topicFilters.every((item) => account.metadata.topics.includes(item)) && conversationFilters.every((item) => account.metadata.conversationTypes.includes(item)) && haystack.includes(query.toLowerCase());
  })), [accounts, domain, status, project, quality, query, versionAfter, roleFilters, topicFilters, conversationFilters]);
  function replaceMetadata(metadata: AccountMetadata) { setAccounts((current) => current.map((account) => account.email === metadata.email ? { ...account, metadata } : account)); setSelected((current) => current?.email === metadata.email ? { ...current, metadata } : current); }
  function edit(account: AccountView) { setSelected(account); setDetailOpen(false); setEditOpen(true); }
  async function logout() { await api("/auth/logout", { method: "POST" }); onLogout(); }
  return <main className="min-h-screen"><header className="border-b bg-card"><div className="mx-auto flex max-w-[1800px] flex-col gap-4 px-4 py-6 lg:px-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium"><ShieldCheckIcon />{t(locale, "page.kicker")}</div><h1 className="text-3xl font-bold tracking-tight">{t(locale, "page.title")}</h1><p className="mt-1 text-muted-foreground">{t(locale, "page.description")}</p></div><div className="flex flex-wrap gap-2"><Button asChild><a href={WEBMAIL_URL} target="_blank" rel="noreferrer"><ExternalLinkIcon data-icon="inline-start" />{t(locale, "page.webmail")}</a></Button><Button variant="outline" asChild><a href="/testmails/testmails.md"><DownloadIcon data-icon="inline-start" />{t(locale, "page.markdown")}</a></Button><TaxonomySettings taxonomies={taxonomies} locale={locale} onSaved={setTaxonomies} /><Button variant="outline" onClick={() => onLocaleChange(locale === "de" ? "en" : "de")} aria-label={t(locale, "page.language")}><LanguagesIcon data-icon="inline-start" />{locale === "de" ? "EN" : "DE"}</Button><Button variant="ghost" onClick={logout}><LogOutIcon data-icon="inline-start" />{t(locale, "page.logout")}</Button></div></div>
    <div className="grid gap-3 lg:grid-cols-[minmax(18rem,1fr)_auto_auto_auto_auto]"><div className="relative"><SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input className="pl-10" placeholder={t(locale, "page.search")} value={query} onChange={(event) => setQuery(event.target.value)} /></div><Select value={status} onValueChange={(value) => setStatus(value as typeof status)}><SelectTrigger className="w-full lg:w-40"><SelectValue placeholder={t(locale, "page.status")} /></SelectTrigger><SelectContent><SelectGroup>{lifecycleValues.map((value) => <SelectItem key={value} value={value}>{value === "all" ? t(locale, "page.all") : labelLifecycle(locale, value)}</SelectItem>)}</SelectGroup></SelectContent></Select><Select value={project} onValueChange={(value) => setProject(value as typeof project)}><SelectTrigger className="w-full lg:w-36"><SelectValue placeholder={t(locale, "page.project")} /></SelectTrigger><SelectContent><SelectGroup>{projectValues.map((value) => <SelectItem key={value} value={value}>{value === "all" ? t(locale, "page.all") : labelProject(locale, value)}</SelectItem>)}</SelectGroup></SelectContent></Select><Select value={quality} onValueChange={(value) => setQuality(value as typeof quality)}><SelectTrigger className="w-full lg:w-36"><SelectValue placeholder={t(locale, "page.testData")} /></SelectTrigger><SelectContent><SelectGroup>{fixtureValues.map((value) => <SelectItem key={value} value={value}>{value === "all" ? t(locale, "page.all") : labelFixture(locale, value)}</SelectItem>)}</SelectGroup></SelectContent></Select><VersionBulkAction accounts={accounts} locale={locale} onMarked={(emails) => setAccounts((current) => current.map((account) => emails.includes(account.email) ? { ...account, metadata: { ...account.metadata, lifecycleStatus: "delete_candidate" } } : account))} /></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Input aria-label={locale === "de" ? "Konten nach Version filtern" : "Filter accounts by version"} placeholder={locale === "de" ? "Liste: Version >" : "List: version >"} value={versionAfter} onChange={(event) => setVersionAfter(event.target.value)} /><MultiSelect label={locale === "de" ? "Rollen filtern" : "Filter roles"} options={taxonomies.roles} value={roleFilters} onChange={setRoleFilters} locale={locale} /><MultiSelect label={locale === "de" ? "Themen filtern" : "Filter topics"} options={taxonomies.topics} value={topicFilters} onChange={setTopicFilters} formatOption={(value) => labelTopic(locale, value)} locale={locale} /><MultiSelect label={locale === "de" ? "Konversationen filtern" : "Filter conversations"} options={taxonomies.conversationTypes} value={conversationFilters} onChange={setConversationFilters} locale={locale} /></div>
    <div className="max-w-full overflow-x-auto pb-1"><ToggleGroup type="single" value={domain} onValueChange={(value) => value && setDomain(value)} variant="outline" className="w-max justify-start">{domains.map((value) => <ToggleGroupItem key={value} value={value} className={`domain-filter ${value === "all" ? "domain-neutral" : domainClass(value)}`}>{value === "all" ? t(locale, "page.all") : value}</ToggleGroupItem>)}</ToggleGroup></div></div></header>
    <section className="mx-auto flex max-w-[1800px] flex-col gap-4 px-4 py-6 lg:px-8"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{t(locale, "page.filteredCount", { shown: filtered.length, total: accounts.length })}</p><div className="flex gap-2"><Badge variant="outline">150 S/MIME</Badge><Badge variant="secondary">30 {locale === "de" ? "Vergleichskonten" : "comparison accounts"}</Badge></div></div>{accounts.length !== 180 && <Alert variant="destructive"><AlertTitle>{locale === "de" ? "Accountbestand unvollständig" : "Account set incomplete"}</AlertTitle><AlertDescription>{locale === "de" ? "Erwartet werden 180 eindeutige Konten." : "Expected 180 unique accounts."}</AlertDescription></Alert>}{filtered.length ? <><AccountTable accounts={filtered} taxonomies={taxonomies} locale={locale} onSaved={replaceMetadata} onDetail={(account) => { setSelected(account); setDetailOpen(true); }} onEdit={edit} /><div className="grid gap-4 sm:grid-cols-2">{filtered.map((account) => <AccountCard key={account.email} account={account} taxonomies={taxonomies} locale={locale} onSaved={replaceMetadata} onDetail={() => { setSelected(account); setDetailOpen(true); }} onEdit={() => edit(account)} />)}</div></> : <Card><CardContent><Empty><EmptyHeader><EmptyTitle>{t(locale, "page.noAccounts")}</EmptyTitle><EmptyDescription>{t(locale, "page.adjustFilters")}</EmptyDescription></EmptyHeader></Empty></CardContent></Card>}</section>
    <AccountDetailSheet account={selected} locale={locale} open={detailOpen} onOpenChange={setDetailOpen} onEdit={() => selected && edit(selected)} /><MetadataEditor account={selected} taxonomies={taxonomies} locale={locale} open={editOpen} onOpenChange={setEditOpen} onSaved={replaceMetadata} />
  </main>;
}

function compareVersions(left: string, right: string) { const a = left.split(".").map(Number), b = right.split(".").map(Number); for (let index = 0; index < 3; index += 1) { const difference = (a[index] ?? 0) - (b[index] ?? 0); if (difference) return difference; } return 0; }
