import { useState } from "react";
import { ExternalLinkIcon, EyeIcon, EyeOffIcon, PencilIcon } from "lucide-react";
import { t, type Locale } from "@/i18n";
import { domainClass } from "@/presentation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import type { AccountMetadata, AccountView, Taxonomies } from "@/types";
import { CopyButton } from "./copy-button";
import { InlineFixtureSelect, InlineProjectSelect, InlineStatusSelect, InlineTaxonomySelect } from "./inline-metadata-controls";
import { OtpAccess } from "./otp-access";

export function AccountCard({ account, taxonomies, locale, onSaved, onDetail, onEdit }: { account: AccountView; taxonomies: Taxonomies; locale: Locale; onSaved: (metadata: AccountMetadata) => void; onDetail: () => void; onEdit: () => void }) {
  const [revealed, setRevealed] = useState(false); const domain = domainClass(account.domain);
  return <Card className={`domain-row min-w-0 ${domain} md:hidden`} onDoubleClick={onEdit}><CardHeader><div className="flex min-w-0 items-start justify-between gap-2"><div className="min-w-0"><CardTitle><Button variant="outline" size="sm" className="max-w-full" onClick={onDetail}><span className="truncate">{account.displayName}</span><ExternalLinkIcon data-icon="inline-end" /></Button></CardTitle><CardDescription className="mt-2 truncate"><a href="https://mail.dreambau.com/" target="_blank" rel="noreferrer" className="font-mono underline underline-offset-4">{account.email}</a></CardDescription></div><Badge variant="outline" className="domain-badge shrink-0">{account.domain}</Badge></div></CardHeader><CardContent className="flex min-w-0 flex-col gap-3"><div className="flex min-w-0 items-center justify-between rounded-lg bg-muted p-2"><code className="truncate text-xs">{revealed ? account.password : "••••••••••••••••"}</code><div className="flex shrink-0"><Button variant="ghost" size="icon-sm" onClick={() => setRevealed(!revealed)} aria-label={locale === "de" ? "Passwort anzeigen oder maskieren" : "Show or hide password"}>{revealed ? <EyeOffIcon /> : <EyeIcon />}</Button><CopyButton value={account.password} label={locale === "de" ? "Passwort kopieren" : "Copy password"} compact /></div></div><OtpAccess account={account} locale={locale} compact /><div className="grid min-w-0 grid-cols-[minmax(0,1fr)_minmax(0,1fr)] gap-2"><InlineProjectSelect account={account} locale={locale} onSaved={onSaved} /><InlineStatusSelect account={account} locale={locale} onSaved={onSaved} /><InlineTaxonomySelect account={account} locale={locale} kind="roles" options={taxonomies.roles} onSaved={onSaved} /><InlineTaxonomySelect account={account} locale={locale} kind="topics" options={taxonomies.topics} onSaved={onSaved} /><InlineTaxonomySelect account={account} locale={locale} kind="conversationTypes" options={taxonomies.conversationTypes} onSaved={onSaved} /><InlineFixtureSelect account={account} locale={locale} onSaved={onSaved} /></div></CardContent><CardFooter className="justify-between"><CopyButton value={account.email} label="E-Mail" /><Button variant="outline" onClick={onEdit}><PencilIcon data-icon="inline-start" />{t(locale, "page.edit")}</Button></CardFooter></Card>;
}
