import { useState } from "react";
import { ExternalLinkIcon, EyeIcon, EyeOffIcon, LockIcon, LockOpenIcon, MoreHorizontalIcon } from "lucide-react";
import { labelConversation, labelFixture, labelLifecycle, labelProject, labelRole, labelTopic, t, type Locale } from "@/i18n";
import { domainClass } from "@/presentation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { AccountMetadata, AccountView, HumanEntitlements, LinkedTestAccount, Taxonomies } from "@/types";
import { CopyButton } from "./copy-button";
import { FavoriteButton } from "./favorite-button";
import { OtpAccess } from "./otp-access";

const WEBMAIL_URL = "https://mail.dreambau.com/";

export function AccountTable({ accounts, taxonomies, locale, onDetail, onEdit, onSaved, orisoProvisioningEnvironments = [], onProvisioned, favorites = new Set<string>(), onToggleFavorite, favoritesReady = true }: { accounts: AccountView[]; taxonomies: Taxonomies; locale: Locale; onDetail: (account: AccountView) => void; onEdit: (account: AccountView) => void; onSaved: (metadata: AccountMetadata) => void; orisoProvisioningEnvironments?: HumanEntitlements["orisoProvisioning"]["environments"]; onProvisioned?: (email: string, linked: LinkedTestAccount) => void; favorites?: ReadonlySet<string>; favoritesReady?: boolean; onToggleFavorite?: (email: string) => void }) {
  const [revealed, setRevealed] = useState<Set<string>>(new Set());
  const toggle = (email: string) => setRevealed((current) => { const next = new Set(current); next.has(email) ? next.delete(email) : next.add(email); return next; });
  return <div className="hidden overflow-hidden rounded-xl border bg-card md:block"><Table className="table-fixed min-w-[60rem]"><TableHeader><TableRow><TableHead className="w-[26%]">{t(locale, "page.identity")}</TableHead><TableHead className="w-[26%]">{t(locale, "page.access")}</TableHead><TableHead className="w-[38%]">{locale === "de" ? "Einordnung" : "Classification"}</TableHead><TableHead className="w-[10%] text-right">{t(locale, "page.actions")}</TableHead></TableRow></TableHeader><TableBody>{accounts.map((account) => {
    const domain = domainClass(account.domain);
    return <TableRow key={account.email} className={domain} onDoubleClick={() => onEdit(account)} title={locale === "de" ? "Doppelklick zum Bearbeiten" : "Double-click to edit"}>
      <TableCell className="min-w-0 align-top whitespace-normal"><div className="mb-2 flex min-w-0 flex-wrap items-center gap-1.5">{onToggleFavorite && <FavoriteButton disabled={!favoritesReady} favorite={favorites.has(account.email)} onToggle={() => onToggleFavorite(account.email)} locale={locale} name={account.displayName} />}<Button variant="outline" size="sm" className="min-w-0 max-w-full justify-start overflow-hidden font-semibold" onClick={() => onDetail(account)}><span className="min-w-0 truncate">{account.displayName}</span><ExternalLinkIcon className="shrink-0" data-icon="inline-end" /></Button><Badge variant="outline" className="domain-badge max-w-full truncate">{account.domain}</Badge></div><div className="mt-2 flex min-w-0 items-center gap-1"><a href={WEBMAIL_URL} target="_blank" rel="noreferrer" className="min-w-0 truncate font-mono text-xs font-medium underline decoration-muted-foreground/40 underline-offset-4 hover:decoration-foreground" title={account.email} aria-label={`${t(locale, "page.openMail")}: ${account.email}`}>{account.email}</a><CopyButton value={account.email} label={locale === "de" ? "E-Mail kopieren" : "Copy email"} compact /></div><div className="mt-1 flex min-w-0 items-center gap-1 text-xs text-muted-foreground">{account.encryption.state === "encrypted" ? <LockIcon className="size-3.5 shrink-0" /> : <LockOpenIcon className="size-3.5 shrink-0" />}<span className="min-w-0 truncate">{account.encryption.state === "encrypted" ? t(locale, "page.encrypted") : t(locale, "page.unencrypted")}</span></div></TableCell>
      <TableCell className="min-w-0 align-top whitespace-normal"><div className="text-xs font-medium text-muted-foreground">{locale === "de" ? "Mail-Passwort" : "Mailbox password"}</div><div className="flex min-w-0 items-center gap-1"><code className="min-w-0 truncate text-xs text-muted-foreground">{revealed.has(account.email) ? account.password : "••••••••••••••••"}</code><Button variant="ghost" size="icon-sm" onClick={() => toggle(account.email)} aria-label={locale === "de" ? "Mail-Passwort anzeigen oder maskieren" : "Show or hide mailbox password"}>{revealed.has(account.email) ? <EyeOffIcon /> : <EyeIcon />}</Button><CopyButton value={account.password} label={locale === "de" ? "Mail-Passwort kopieren" : "Copy mailbox password"} compact /></div><div className="mt-2"><OtpAccess account={account} locale={locale} compact orisoProvisioningEnvironments={orisoProvisioningEnvironments} onProvisioned={onProvisioned} /></div></TableCell>
      <TableCell className="min-w-0 align-top whitespace-normal"><div className="flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1 text-sm"><span className="font-medium">{labelProject(locale, account.metadata.project)}</span><span className="text-muted-foreground" aria-hidden>·</span><Badge variant={account.metadata.lifecycleStatus === "active" ? "default" : "secondary"}>{labelLifecycle(locale, account.metadata.lifecycleStatus)}</Badge>{account.metadata.shippedVersion && <span className="text-xs text-muted-foreground">v{account.metadata.shippedVersion}</span>}<span className="text-xs text-muted-foreground">{labelFixture(locale, account.metadata.fixtureQuality)} · {account.metadata.sampleFileCount} {t(locale, "page.files")}</span></div>{(account.metadata.roles.length + account.metadata.topics.length + account.metadata.conversationTypes.length) > 0 && <div className="mt-2 flex min-w-0 flex-wrap gap-1">{account.metadata.roles.map((value) => <span key={`r-${value}`} className="tag-pill tag-role">{labelRole(locale, value)}</span>)}{account.metadata.topics.map((value) => <span key={`t-${value}`} className="tag-pill tag-topic">{labelTopic(locale, value)}</span>)}{account.metadata.conversationTypes.map((value) => <span key={`c-${value}`} className="tag-pill tag-conversation">{labelConversation(locale, value)}</span>)}</div>}</TableCell>
      <TableCell className="align-top"><div className="flex justify-end gap-1"><Button asChild variant="ghost" size="icon-sm"><a href={WEBMAIL_URL} target="_blank" rel="noreferrer" aria-label={`${t(locale, "page.openMail")}: ${account.email}`}><ExternalLinkIcon /></a></Button><CopyButton value={[account.displayName, account.email, account.password, account.domain, account.metadata.shippedVersion, account.metadata.lifecycleStatus, account.metadata.project].join("\t")} label={locale === "de" ? "Zeile kopieren" : "Copy row"} compact /><Button variant="ghost" size="icon-sm" onClick={() => onEdit(account)} aria-label={locale === "de" ? "Metadaten bearbeiten" : "Edit metadata"}><MoreHorizontalIcon /></Button></div></TableCell>
    </TableRow>;
  })}</TableBody></Table></div>;
}
