apiVersion: v1
kind: Secret
metadata:
  name: etherpad-secret
  namespace: wcr
type: Opaque
stringData:
  # Database credentials
  DB_USER: "etherpad"
  DB_PASS: "P4D0bjt2MASjMy5d0CdYSre+hZNISfOB1RhS7pFOQsQ="
  DB_NAME: "etherpad"
  
  # Admin credentials for Etherpad
  ADMIN_PASSWORD: "2sGH6syYR+Ie9uGCmmoc3Ib9HrFNjIrH"
  
  # Session key (64 chars hex)
  SESSION_KEY: "deff8108a0849db7c80f840572d0ad331c01c52d068250a97cf047962d6a08ae"
  
  # API key
  API_KEY: "67e0f8fcd502fd6a1f3e12af2e9b74f9e2c32db3bb4919a1a21cd2a3271f3e41"
