apiVersion: v1
data:
  APP_DEBUG: ZmFsc2U=
  APP_ENV: cHJvZHVjdGlvbg==
  APP_KEY: YmFzZTY0OjYrY0xnbFVlbmp6dWpxNXNWeDRXYVRQcGQ1TVByNXRpeVZkZUZLeHRMRTQ9
  APP_URL: aHR0cHM6Ly9pbnZvaWNlLndjcmJ1c2luZXNzLm9ubGluZQ==
  DB_DATABASE: bmluamE=
  DB_HOST: bXlzcWwud2NyLnN2Yy5jbHVzdGVyLmxvY2Fs
  DB_PASSWORD: V0NSX05pbmphX1Bhc3NfMjAyNF9DaGFuZ2VfTWU=
  DB_PORT: MzMwNg==
  DB_USERNAME: bmluamE=
  MAIL_ENCRYPTION: dGxz
  MAIL_FROM_ADDRESS: bm9yZXBseUBpbnZvaWNlLndjcmJ1c2luZXNzLm9ubGluZQ==
  MAIL_FROM_NAME: V0NSIEJ1c2luZXNz
  MAIL_HOST: c210cC5nbWFpbC5jb20=
  MAIL_MAILER: c210cA==
  MAIL_PASSWORD: eW91ci1hcHAtcGFzc3dvcmQ=
  MAIL_PORT: NTg3
  MAIL_USERNAME: eW91ci1lbWFpbEBnbWFpbC5jb20=
  PDF_GENERATOR: c25hcHBkZg==
  PHANTOMJS_PDF_GENERATION: ZmFsc2U=
  REQUIRE_HTTPS: dHJ1ZQ==
  TRUSTED_PROXIES: Kg==
  VIEW_COMPILED_PATH: L3Zhci93d3cvYXBwL3N0b3JhZ2UvZnJhbWV3b3JrL3ZpZXdz
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"invoiceninja-secret","namespace":"wcr"},"stringData":{"APP_DEBUG":"false","APP_ENV":"production","APP_KEY":"base64:6+cLglUenjzujq5sVx4WaTPpd5MPr5tiyVdeFKxtLE4=","APP_URL":"https://invoice.wcrbusiness.online","DB_DATABASE":"ninja","DB_HOST":"mysql.wcr.svc.cluster.local","DB_PASSWORD":"WCR_Ninja_Pass_2024_Change_Me","DB_PORT":"3306","DB_USERNAME":"ninja","MAIL_ENCRYPTION":"tls","MAIL_FROM_ADDRESS":"noreply@invoice.wcrbusiness.online","MAIL_FROM_NAME":"WCR Business","MAIL_HOST":"smtp.gmail.com","MAIL_MAILER":"smtp","MAIL_PASSWORD":"your-app-password","MAIL_PORT":"587","MAIL_USERNAME":"your-email@gmail.com","PDF_GENERATOR":"snappdf","PHANTOMJS_PDF_GENERATION":"false","REQUIRE_HTTPS":"true","TRUSTED_PROXIES":"*","VIEW_COMPILED_PATH":"/var/www/app/storage/framework/views"},"type":"Opaque"}
  creationTimestamp: "2025-11-08T14:40:06Z"
  name: invoiceninja-secret
  namespace: wcr
  resourceVersion: "8781"
  uid: 72d7667b-8b5c-4f46-b6cb-444527b8d523
type: Opaque
