apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data-pvc
  namespace: wcr
  labels:
    app: nocodb
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

