import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {buildReferences} from './references-page.mjs';
import {buildGlossary} from './glossary-page.mjs';
const root=path.resolve(import.meta.dirname,'..');
const data=JSON.parse(fs.readFileSync(path.join(root,'content.json'),'utf8'));
const refs=buildReferences(data),gloss=buildGlossary(data);
fs.mkdirSync(path.join(root,'site/referenzen'),{recursive:true});fs.mkdirSync(path.join(root,'site/glossar'),{recursive:true});fs.writeFileSync(path.join(root,'site/referenzen/index.html'),refs);fs.writeFileSync(path.join(root,'site/glossar/index.html'),gloss);
const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.cpSync(path.join(root,'site'),dist,{recursive:true});
const files=[];function walk(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name);if(fs.statSync(file).isDirectory())walk(file);else{const b=fs.readFileSync(file);files.push({path:path.relative(dist,file),bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')});}}}walk(dist);fs.writeFileSync(dist+'.json',JSON.stringify({files,totalBytes:files.reduce((n,f)=>n+f.bytes,0)},null,2)+'\n');console.log('Website: '+files.length+' files, '+(data.references.current_projects.length+data.references.older_references.length)+' references, '+data.glossary.terms.length+' terms, '+data.glossary.questions.length+' questions.');
