import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'), data=JSON.parse(fs.readFileSync(path.join(root,'content.json'),'utf8'));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav='<nav class="foot" aria-label="Website"><a href="/">Startseite</a><a href="/referenzen/">Referenzen</a><a href="/teamwork/">Teamwork</a><a href="/glossar/">Glossar</a><a href="mailto:info@dreambau.com">Kontakt</a></nav>';
function page(title,sub,body,kind){return `<!doctype html><html lang="de" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#06080d"><title>${title} · dreambau.com</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/website-assets/website.css"><script src="/website-assets/glossary-suggestions.js" defer></script><script src="/website-assets/website.js" defer></script></head><body class="${kind}"><header class="top"><a class="pill" href="/">‹ Startseite</a><h1 class="ttl">${title}<i class="caret" aria-hidden="true"></i></h1><p class="kicker">${sub}</p></header>${body}${nav}</body></html>\n`;}
const tagLabels=data.references.tag_labels;
const entries=[...data.references.current_projects.map(e=>({...e,title:e.name,year:'Jetzt',current:true})),...data.references.older_references.map(e=>({...e,title:e.client,current:false}))];
function entry(e,i){const image=e.images?.[0],src=image?'/website-assets/portfolio/'+e.id+'.webp':null;
 return `<article class="project ${e.current?'cur':'old'}" id="project-${e.id}"><header><span class="number">${String(i+1).padStart(2,'0')}</span><span class="year">${esc(e.year)}</span><h2>${esc(e.title)}</h2>${e.current?'':'<span class="tag en">EN</span>'}</header><div class="tags">${e.tags.map(t=>`<span class="tag">${esc(tagLabels[t]||t)}</span>`).join('')}</div>${e.current?'<p class="pending">Kurztext folgt</p>':`<p lang="en" dir="ltr">${esc(e.scope)}</p>`}${e.links?.filter(l=>l.reachability_verified===true).map(l=>`<a class="lk" href="${esc(l.href_candidate)}" rel="noreferrer">${esc(l.label)}</a>`).join('')||''}${e.detail_text||src?`<details><summary class="pill">Details ansehen</summary>${e.detail_text?`<p class="original" lang="en" dir="ltr">${esc(e.detail_text)}</p>`:''}${src?`<img loading="lazy" src="${src}" alt="${esc(e.title)} · Originalansicht aus dem Portfolio">`:''}</details>`:''}</article>`;}
const years=['2017','2018','//','2023','2024','Jetzt'];
const timeline=`<section class="timeline" aria-label="Zeitstrahl"><div class="c-band">${years.map(y=>`<span class="seg ${y==='Jetzt'?'now':''}">${y}</span>`).join('')}</div><ol class="c-nodes">${entries.map((e,i)=>`<li class="node ${i%2?'lower':''} ${e.current?'cur':''} node-${i}"><a class="nd" href="#project-${e.id}"><span class="orb"><span class="ex">${String(i+1).padStart(2,'0')}</span></span><span class="node-year">${esc(e.year)}</span><span class="lb">${esc(e.title)}</span></a></li>`).join('')}</ol></section>`;
const search='<div class="search"><label for="search">Suchen</label><input id="search" type="search" placeholder="Projekt, Wort oder Frage"><p id="results" role="status"></p></div>';
const refs=page('Referenzen','Was gebaut wurde und für wen.',search+timeline+'<main class="projects">'+entries.map(entry).join('')+'</main>','references');
const glossary=data.glossary,terms=glossary.terms, questions=glossary.questions;
const asks='<section class="ask"><h2>Ich will …</h2><div class="cols">'+glossary.groups.map(g=>`<section class="grp"><h3>${esc(g.name)}</h3><ul class="rows">${questions.filter(q=>q.group===g.id).map(q=>`<li><a class="opt" href="#question-${q.id}">${esc(q.text)}</a></li>`).join('')}</ul></section>`).join('')+'</div></section>';
const answers='<section class="answers" aria-label="Antworten">'+questions.map(q=>`<article class="answer term" id="question-${q.id}"><h3>Ich will ${esc(q.text)}</h3><p>${esc(q.answer.what)}</p><p>${esc(q.answer.where)}</p><p>${esc(q.answer.whatFor)}</p><a class="lk" href="#term-${q.word}">${esc(terms.find(t=>t.id===q.word).name)}</a></article>`).join('')+'</section>';
const words='<section class="words" aria-label="Wörter A bis Z"><h2>A–Z · '+terms.length+' Wörter</h2>'+terms.slice().sort((a,b)=>a.name.localeCompare(b.name,'de')).map(t=>`<article id="term-${t.id}" class="term"><h3>${esc(t.name)} ${t.english_alias?`<span class="tag">${esc(t.english_alias)}</span>`:''}</h3><p>${esc(t.definition)}</p><p class="related">${t.related.filter(id=>terms.some(r=>r.id===id)).map(id=>`<a href="#term-${id}">${esc(terms.find(r=>r.id===id).name)}</a>`).join(' · ')}</p></article>`).join('')+'</section>';
const gloss=page('Glossar','Ich will …',search+'<main class="mainc">'+asks+'<div>'+answers+words+'</div>'+'</main>','glossary');
fs.mkdirSync(path.join(root,'site/referenzen'),{recursive:true});fs.mkdirSync(path.join(root,'site/glossar'),{recursive:true});fs.writeFileSync(path.join(root,'site/referenzen/index.html'),refs);fs.writeFileSync(path.join(root,'site/glossar/index.html'),gloss);
fs.writeFileSync(path.join(root,'site/website-assets/glossary-suggestions.js'),'window.glossarySuggestions='+JSON.stringify(glossary.avoid)+';\n');
const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.cpSync(path.join(root,'site'),dist,{recursive:true});
const files=[];function walk(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name);if(fs.statSync(file).isDirectory())walk(file);else{const b=fs.readFileSync(file);files.push({path:path.relative(dist,file),bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')});}}}walk(dist);fs.writeFileSync(dist+'.json',JSON.stringify({files,totalBytes:files.reduce((n,f)=>n+f.bytes,0)},null,2)+'\n');console.log('Website: '+files.length+' files, '+entries.length+' references, '+terms.length+' terms, '+questions.length+' questions.');
