import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
const root=path.resolve(import.meta.dirname,'..'), dist=path.resolve(root,'../landing/dist/apex'), external=process.env.BASE_URL, scratch=fs.mkdtempSync(path.join(os.tmpdir(),'website-check-')), name='website-check-'+process.pid;
const csp="default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'";
let browser,base=external;
const artifact=path.join(root,'test-results',external?'production':'local');fs.mkdirSync(artifact,{recursive:true});
let checks=0;const ok=(name,value)=>{assert(value,name);checks++;console.log('PASS '+name);};
try{
 if(!external){const conf=path.join(scratch,'default.conf');fs.writeFileSync(conf,`server{listen 80;root /site;access_log off;include /etc/nginx/mime.types;add_header Content-Security-Policy "${csp}" always;add_header Cache-Control no-store always;add_header X-Content-Type-Options nosniff always;location = /{try_files /index.html =404;}location /homepage-assets/{alias /site/;}location = /referenzen{return 308 /referenzen/;}location = /glossar{return 308 /glossar/;}location ~ ^/(?:referenzen|glossar|website-assets)/(?:.*/)?\\.{return 404;}location /referenzen/{try_files $uri $uri/ =404;autoindex off;}location /glossar/{try_files $uri $uri/ =404;autoindex off;}location /website-assets/{try_files $uri =404;autoindex off;}location /{return 404;}}`);execFileSync('docker',['run','-d','--rm','--name',name,'-p','127.0.0.1::80','--mount',`type=bind,source=${dist},target=/site,readonly`,'--mount',`type=bind,source=${conf},target=/etc/nginx/conf.d/default.conf,readonly`,'nginx:1.27-alpine'],{stdio:'pipe'});base='http://127.0.0.1:'+execFileSync('docker',['port',name,'80/tcp'],{encoding:'utf8'}).trim().split(':').pop();}
 for(let n=0;n<50;n++){try{if((await fetch(base+'/')).status===200)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 for(const route of ['/referenzen/','/glossar/']){const r=await fetch(base+route);ok(route+' 200',r.status===200);ok(route+' own-origin policy',r.headers.get('content-security-policy')===csp);const html=await r.text();ok(route+' no inline executable content',!/<style|\sstyle=|\son[a-z]+=|<script(?![^>]*src=)/i.test(html));}
 for(const route of ['/referenzen/missing','/glossar/.hidden','/website-assets/missing.js'])ok(route+' 404',(await fetch(base+route)).status===404);
 for(const route of ['/referenzen','/glossar'])ok(route+' canonical redirect',(await fetch(base+route,{redirect:'manual'})).status===308);
 browser=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required']});
 for(const [device,width,height] of [['desktop',1440,900],['tablet',820,1180],['phone',390,844]]){
  const page=await browser.newPage({viewport:{width,height},hasTouch:device!=='desktop',isMobile:device!=='desktop',reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto(base+'/?anim=4k');await page.waitForFunction(()=>document.documentElement.classList.contains('ready'));
  await page.locator('#site-menu summary').click();ok(device+' menu links',await page.locator('#site-menu nav a').count()===6);await page.screenshot({path:path.join(artifact,device+'-menu.png')});
  await page.keyboard.press('Escape');ok(device+' menu Escape',!await page.locator('#site-menu').evaluate(e=>e.open));
  await page.locator('#source-entry').click();await page.locator('.code-view').waitFor({state:'visible'});await page.waitForTimeout(200);ok(device+' full source in calm state',await page.locator('.cv-text').allTextContents().then(t=>t.join('')===fs.readFileSync(path.join(dist,'p/4k.js'),'utf8')));await page.screenshot({path:path.join(artifact,device+'-source.png')});
  await page.locator('#cv-size').click();ok(device+' comparisons',await page.locator('.comparison-row').count()===3);await page.screenshot({path:path.join(artifact,device+'-comparison.png')});await page.keyboard.press('Escape');ok(device+' closes top dialog',await page.locator('.code-view').evaluate(e=>e.open));await page.keyboard.press('Escape');ok(device+' returns focus',await page.locator('#source-entry').evaluate(e=>e===document.activeElement));
  for(const route of ['/referenzen/','/glossar/']){await page.goto(base+route);if(route==='/glossar/'){await page.locator('#search').fill('Deploy');ok(device+' Deploy guidance',(await page.locator('#results').innerText()).includes('Veröffentlichen'));await page.locator('#search').fill('Glossar');await page.locator('#term-glossar a[href="#term-startseite"]').click();ok(device+' related term reveals filtered target',await page.locator('#term-startseite').isVisible()&&await page.locator('#search').inputValue()==='');await page.locator('#search').fill('');ok(device+' question-specific login answer',(await page.locator('#question-login-brauche').innerText()).includes('Teamwork selbst braucht kein Login.'));}if(route==='/referenzen/')ok(device+' no unverified project links',await page.locator('.cur a.lk').count()===0);ok(device+route+' no sideways scroll',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(artifact,device+(route.includes('referenzen')?'-references':'-glossary')+'.png')});await page.getByRole('textbox',{name:'Suchen'}).or(page.getByRole('searchbox',{name:'Suchen'})).fill('zzzxmissing');ok(device+route+' empty search',await page.locator('#results').textContent()==='Keine Treffer');await page.locator('#search').fill('');await page.getByRole('link',{name:'‹ Startseite'}).click();ok(device+route+' back to home',new URL(page.url()).pathname==='/');}
  ok(device+' no browser errors',errors.length===0);await page.close();
 }
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}}),page=await nojs.newPage();for(const route of ['/','/referenzen/','/glossar/']){await page.goto(base+route);ok(route+' no-JS content',route==='/'?await page.locator('h1').isVisible():await page.locator(route.includes('referenzen')?'.project':'.words .term').count()===(route.includes('referenzen')?12:26));if(route==='/'){await page.locator('summary').click();ok('no-JS menu',await page.locator('nav a[href="/referenzen/"]').isVisible());}}await nojs.close();
 // Isolated manual-clock render regression against the original ungated shader, with identical fixtures.
 const old=fs.readFileSync(path.join(dist,'p/4k.js'),'utf8').replace('dot(b*clamp(.5-','dot(clamp(.5-');
 const frames=[];for(const original of [true,false]){const p=await browser.newPage({viewport:{width:640,height:360}});if(original)await p.route('**/p/4k.js',r=>r.fulfill({status:200,contentType:'application/javascript',body:old}));await p.goto(base+'/?anim=4k&test=1');await p.waitForFunction(()=>window.Dream?.test);await p.evaluate(()=>Dream.test.ready);const shots={};for(const t of [10,25,40,53]){shots[t]=await p.evaluate(t=>Dream.test.thumb(t,128,72),t);if(t===10||t===53){await p.evaluate(t=>Dream.test.seek(t),t);await p.screenshot({path:path.join(artifact,(original?'before':'after')+'-rohbau-'+t+'.png')});}}frames.push(shots);await p.close();}
 for(const t of [10,25,40])ok('premature text removed at '+t+'s',frames[0][t].some((v,i)=>Math.abs(v-frames[1][t][i])>.01));ok('final shader picture unchanged at 53s',frames[0][53].every((v,i)=>v===frames[1][53][i]));
 fs.writeFileSync(path.join(artifact,'result.json'),JSON.stringify({result:'PASS',checks,base},null,2));console.log(checks+' checks passed.');
}finally{await browser?.close();if(!external){try{execFileSync('docker',['rm','-f',name],{stdio:'ignore'});}catch{}}fs.rmSync(scratch,{recursive:true,force:true});}
