// Selected Wegweiser composition. Content remains in the settled public catalogue.
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function buildGlossary(data){
 const g=data.glossary,terms=new Map(g.terms.map(t=>[t.id,t]));
 // Catalogue identifiers currently use validated slugs; escape them at every HTML boundary as well.
 for(const q of g.questions)if(!terms.has(q.word))throw new Error('Glossary question "'+q.id+'" refers to unknown word "'+q.word+'".');
 const action=a=>{const target=a?.btn?.[1];return target&&(/^\/(?!\/)/.test(target)||/^https:\/\/dreambau\.com(?:\/|$)/.test(target))?`<a href="${esc(target)}">${esc(a.btn[0])}</a>`:'';};
 const fallback=`<main class="fallback"><a href="/">‹ Startseite</a><h1>Glossar</h1><h2>Ich will …</h2><ul>${g.questions.map(q=>`<li><a href="#question-${esc(q.id)}">${esc(q.text)}</a></li>`).join('')}</ul>${g.questions.map(q=>`<article id="question-${esc(q.id)}"><h2>Ich will ${esc(q.text)}</h2><h3>${esc(q.answer.place)}</h3><dl><dt>Wort</dt><dd><a href="#term-${esc(q.word)}">${esc(terms.get(q.word).name)}</a></dd><dt>Was</dt><dd>${esc(q.answer.what)}</dd><dt>Wo</dt><dd>${esc(q.answer.where)}</dd><dt>Wozu</dt><dd>${esc(q.answer.whatFor)}</dd></dl>${action(q.answer)}</article>`).join('')}<section id="woerter"><h2>Wörter A–Z</h2>${g.terms.slice().sort((a,b)=>a.name.localeCompare(b.name,'de')).map(t=>`<article id="term-${esc(t.id)}"><h3>${esc(t.name)}</h3>${t.english_alias?`<p lang="en">${esc(t.english_alias)}</p>`:''}<p>${esc(t.definition)}</p><p>${t.related.filter(id=>terms.has(id)).map(id=>`<a href="#term-${esc(id)}">${esc(terms.get(id).name)}</a>`).join(' · ')}</p></article>`).join('')}</section></main>`;
 return `<!doctype html><html lang="de" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark"><meta name="theme-color" content="#06080d"><title>Glossar · dreambau.com</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/website-assets/glossary.css"><script src="/website-assets/glossary.js" defer></script></head><body>${fallback}<template id="glossary-data">${esc(JSON.stringify({terms:g.terms,questions:g.questions,avoid:g.avoid}))}</template><div id="stage"><div id="frame"><div id="app"></div></div></div></body></html>\n`;
}
