apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-postgres-pvc
  namespace: wcr
  labels:
    app: shared-postgres
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi



