import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {check,same,run} from '../lib/check.mjs';import {ROOT} from '../lib/paths.mjs';import {launchBrowser,openObserved} from '../lib/browser.mjs';import {startPageServer} from '../lib/page-server.mjs';
const execute=promisify(execFile),pause=(ms)=>new Promise((r)=>setTimeout(r,ms)),dir=fs.mkdtempSync(path.join(os.tmpdir(),'teamwork-chain-'));let browser,server,charlie=503,flapping=false,hits=0;const sockets=new Set();
const zoo=http.createServer((req,res)=>{const name=req.url.slice(1);if(name==='delta')return;const code=name==='alpha'?200:name==='bravo'?404:flapping?(++hits===1?503:200):charlie;res.writeHead(code);res.end();});zoo.on('connection',(socket)=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));});await new Promise((resolve)=>zoo.listen(0,'127.0.0.1',resolve));
const catalogue={format:1,zones:[{id:'zone',name:'Testzone',color:'cyan'}],programs:['alpha','bravo','charlie','delta'].map((id)=>({id,name:id,purpose:'Erfundenes Kettenprogramm',url:'https://'+id+'.example.test/',probe:'http://127.0.0.1:'+zoo.address().port+'/'+id,zone:'zone'}))};const input=path.join(dir,'private.json'),history=path.join(dir,'history');fs.writeFileSync(input,JSON.stringify(catalogue));fs.mkdirSync(history);
try{await run(async()=>{
 server=await startPageServer({list:catalogue});browser=await launchBrowser();const observed=await openObserved(browser),{context,page,seen}=observed;
 const publish=async()=>{await execute('python3',[path.join(ROOT,'status/teamwork_status.py'),'--list',input,'--out',path.join(server.tree.teamwork,'data'),'--history',history,'--connect-timeout','1','--timeout','2','--retry-delay','3'],{timeout:20000});if(process.platform==='darwin')await pause(600);};
 const shown=()=>page.locator('.tile').evaluateAll((nodes)=>nodes.map((node)=>node.dataset.id));
 await publish();await page.goto(server.url);await page.locator('.tile').first().waitFor();same('C52 actual script publishes alpha200 and bravo404 in catalogue order',JSON.parse(fs.readFileSync(path.join(server.tree.teamwork,'data/status.json'))).reachable,['alpha','bravo']);same('C52 page hides failed programs from the served script output',await shown(),['alpha','bravo']);check('C52 hidden names are absent from rendered page text',await page.locator('body').textContent().then((text)=>!text.includes('charlie')&&!text.includes('delta')));
 charlie=200;await publish();await page.reload();await page.locator('[data-id="charlie"]').waitFor();same('C53 recovered program returns after actual status publication',await shown(),['alpha','bravo','charlie']);
 flapping=true;hits=0;await publish();await page.reload();await page.locator('[data-id="charlie"]').waitFor();check('C54 flapping program returns after successful retry in same run',hits===2&&(await shown()).includes('charlie'));
 server.replaceFile('data/status.json',JSON.stringify({format:1,checkedAt:new Date(Date.now()-10860000).toISOString().replace(/\.\d{3}Z$/,'Z'),reachable:[]}));if(process.platform==='darwin')await pause(600);await page.reload();await page.locator('.tile').first().waitFor();check('C55 dead script age shows all four programs as unknown',await page.locator('.tile').count()===4&&await page.locator('.unknown').count()===4&&await page.locator('#banner').isVisible());
 fs.unlinkSync(path.join(server.tree.teamwork,'data/status.json'));if(process.platform==='darwin')await pause(600);await page.reload();await page.locator('.tile').first().waitFor();check('C55 missing status also shows all four marked programs',await page.locator('.unknown').count()===4);
 fs.unlinkSync(path.join(server.tree.teamwork,'data/programs.json'));if(process.platform==='darwin')await pause(600);await page.reload();await page.locator('#retry').waitFor();same('C55 missing catalogue displays approved unavailable state',await page.locator('#message-text').textContent(),'Die Programmliste ist gerade nicht erreichbar.');
 same('C55 no uncaught browser errors',seen.pageErrors,[]);const errors=seen.console.filter((message)=>message.type==='error');check('C55 only expected missing-file 404 console lines occur',errors.length===3&&errors.every((message)=>message.text.includes('404')));
 await context.close();
});}finally{if(browser)await browser.close();if(server)await server.stop();for(const socket of sockets)socket.destroy();await new Promise((resolve)=>zoo.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}
