apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wcr
type: Opaque
stringData:
  # IMPORTANT: Change these passwords in production!
  MYSQL_ROOT_PASSWORD: "WCR_Root_Pass_2024_Change_Me"
  MYSQL_PASSWORD: "WCR_Ninja_Pass_2024_Change_Me"
  MYSQL_DATABASE: "ninja"
  MYSQL_USER: "ninja"

